# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6xmwHASHPBy6KB-UmjbRmSk51Y-odne

## 📦 Install Dependencies
"""

!pip -q install accelerate bitsandbytes datasets huggingface_hub peft scikit-learn transformers trl

"""## 📚 Libraries"""

from collections import Counter
from datasets import load_dataset, concatenate_datasets
from huggingface_hub import login, notebook_login
from google.colab import userdata
import os
from peft import LoraConfig
import numpy as np
import random
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
)
from trl import SFTTrainer
import torch

"""## 🔐 Login to Hugging Face Hub"""

hf_token = userdata.get('HF_Token')

if hf_token:
    login(token=hf_token)
    print("HuggingFace login successful.")
else:
    print("HuggingFace token not found. Please set the HF_TOKEN environment variable or store it in Colab secrets.")

"""## 📥 Load Medical Q and A Dataset"""

# Load Dataset
# https://huggingface.co/datasets/GBaker/MedQA-USMLE-4-options
dataset = load_dataset("GBaker/MedQA-USMLE-4-options")

# Inspect dataset
print(f"\ndataset['train'] head:")
print(dataset["train"][:5])

print("\ndataset['train'] column names:")
print(dataset["train"].column_names)

"""🎲 Reproducibility"""

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

"""## 🧠 Define allowed answer letters and their token IDs"""

LETTER_CHOICES = ["A", "B", "C", "D"]

def row_to_prompt(example):
    """
    Convert a dataset row into:
      - prompt: chat-style instruction + question + options
      - target: the correct letter (A/B/C/D)
    """
    question = example["question"]
    options_dict = example["options"]  # dict like {'A': 'Ampicillin', ...}

    # Ensure options are in A/B/C/D order (some datasets are already)
    letters = sorted(options_dict.keys())

    options_text = "\n".join(f"{letter}. {options_dict[letter]}" for letter in letters)

    prompt = (
        "You are a medical expert answering USMLE-style questions.\n\n"
        f"Question:\n{question}\n\n"
        f"Options:\n{options_text}\n\n"
        "Answer with only the letter (A, B, C, or D)."
    )

    # Provided label is already like 'A', 'B', ...
    target = str(example["answer_idx"]).strip().upper()

    if target not in letters:
        raise ValueError(f"Target {target} not in options {letters}")

    return {"prompt": prompt, "target": target}

"""📌 Train/test split + mapping"""

# Original dataset has only 'train'. Split it.
split = dataset["train"].train_test_split(test_size=0.2, seed=SEED)

train_ds = split["train"].map(row_to_prompt)
test_ds  = split["test"].map(row_to_prompt)

print("\nSplit sizes:", len(train_ds), len(test_ds))
print("Train label distribution:", Counter(train_ds["target"]))
print("Test  label distribution:", Counter(test_ds["target"]))

"""⚖️ Balance the training  set (upsample minority classes)"""

def balance_dataset(ds, label_col="target", seed=42):
    """
    Upsample each class to match the largest class count.
    """
    counts = Counter(ds[label_col])
    max_count = max(counts.values())

    balanced_splits = []
    for label, count in counts.items():
        subset = ds.filter(lambda ex, lbl=label: ex[label_col] == lbl)

        repeat = max_count // count
        remainder = max_count % count

        pieces = [subset] * repeat
        if remainder > 0:
            extra = subset.shuffle(seed=seed).select(range(remainder))
            pieces.append(extra)

        balanced_splits.append(concatenate_datasets(pieces))

    balanced = concatenate_datasets(balanced_splits).shuffle(seed=seed)
    return balanced


train_ds_used = balance_dataset(train_ds, seed=SEED)
print("\n✅ Using balanced train set.")
print("Balanced distribution:", Counter(train_ds_used["target"]))

"""# 🧠 Model"""

MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"

# Load tokenizer
tok = AutoTokenizer.from_pretrained(
    MODEL_ID,
    token=hf_token,
    use_fast=True,
    trust_remote_code=True,
)

# Ensure pad token exists
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

# Baseline model in bf16 (not 4-bit)
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    token=hf_token,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
base_model.eval()

""" 🔢 Token IDs for choices"""

# Chat models often output " A" (leading space) as the next token.
# Score the tokens for " A", " B", " C", " D".
CHOICE_TEXTS = [" A", " B", " C", " D"]

choice_token_ids = []
for s in CHOICE_TEXTS:
    ids = tok(s, add_special_tokens=False).input_ids
    if len(ids) != 1:
        raise ValueError(
            f"Choice text {s!r} tokenized to {ids}. "
            "This script assumes single-token choices for logits scoring."
        )
    choice_token_ids.append(ids[0])

print("\nChoice token ids:", dict(zip(LETTER_CHOICES, choice_token_ids)))

"""🔮 Logits-based prediction helper"""

@torch.no_grad()
def predict_letter_from_logits(model, prompt: str) -> str:
    """
    Build a chat prompt, run model forward once, and choose A/B/C/D
    by comparing next-token logits for the tokens representing " A/B/C/D".
    """
    # Llama-instruct expects a chat template
    messages = [{"role": "user", "content": prompt}]
    prompt_text = tok.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tok(prompt_text, return_tensors="pt").to(model.device)
    outputs = model(**inputs)
    logits = outputs.logits  # [batch, seq_len, vocab]
    next_token_logits = logits[0, -1]  # [vocab]

    scores = [next_token_logits[tok_id].item() for tok_id in choice_token_ids]
    best = int(np.argmax(scores))
    return LETTER_CHOICES[best]

def evaluate_logits_model(model, ds, n=200, label="Model"):
    """
    Evaluate using the logits method on first n examples.
    """
    n = min(n, len(ds))
    y_true = [ds[i]["target"] for i in range(n)]
    y_pred = [predict_letter_from_logits(model, ds[i]["prompt"]) for i in range(n)]

    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0
    )

    print(f"\n{label} (N={n})")
    print(f"  Acc={acc:.3f}  Prec={prec:.3f}  Rec={rec:.3f}  F1={f1:.3f}\n")
    print("Classification report:")
    print(classification_report(y_true, y_pred, labels=LETTER_CHOICES, zero_division=0))

    cm = confusion_matrix(y_true, y_pred, labels=LETTER_CHOICES)
    print("Confusion matrix (rows=true, cols=pred):")
    print("    " + "  ".join(LETTER_CHOICES))
    for i, row in enumerate(cm):
        print(f" {LETTER_CHOICES[i]}  {row}")

    return y_true, y_pred, cm

"""📊 Baseline evaluation"""

baseline_evaluation = evaluate_logits_model(base_model, test_ds, n=200, label="Baseline (bf16, no fine-tune)")

"""⚙️ Install + Reload Model in 4-bit (QLoRA-Ready)"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

qlora_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    token=hf_token,
    device_map="auto",
    quantization_config=bnb_config, # Apply the 4-bit config
    trust_remote_code=True,
)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

"""🧩 Formatting function"""

def formatting_func(examples):
    """
    For SFTTrainer, create a single training string:
      <chat template for prompt> + " A/B/C/D"
    """
    texts = []
    for p, t in zip(examples["prompt"], examples["target"]):
        messages = [{"role": "user", "content": p}]
        prompt_text = tok.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        # Include space so it matches the scoring style
        texts.append(prompt_text + " " + t)
    return {"text": texts}

train_for_sft = train_ds_used.map(
    formatting_func,
    batched=True,
    remove_columns=train_ds_used.column_names,
)

eval_for_sft = test_ds.select(range(min(500, len(test_ds)))).map(
    formatting_func,
    batched=True,
    remove_columns=test_ds.column_names,
)

print("\nSFT example:\n", train_for_sft[0]["text"][:500], "...")

"""🎯 Training Arguments"""

output_dir = "llama31-medqa-qlora"

args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=2e-4,
    num_train_epochs=1,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    logging_steps=20,
    logging_first_step=True,
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    save_total_limit=2,
    bf16=True,
    report_to="none",
    gradient_checkpointing=True,
)

"""🚂 QLoRA SFTTrainer"""

trainer = SFTTrainer(
    model=qlora_model,
    peft_config=lora_config,
    train_dataset=train_for_sft,
    eval_dataset=eval_for_sft,
    args=args,
)

"""🚀 Fine-Tune Model with QLoRA"""

trainer.train()

ft_model = trainer.model
ft_model.eval()

"""Evaluate fine-tuned model (logits method)"""

ft_evaluation = evaluate_logits_model(ft_model, test_ds, n=200, label="Fine-tuned (QLoRA)")

"""Save adapter locally"""

adapter_dir = output_dir
ft_model.save_pretrained(adapter_dir)
tok.save_pretrained(adapter_dir)
print("\n✅ Saved adapter+tokenizer to:", adapter_dir)