# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qE5BcG9C4BQZnNy2k6aRY3bn2OklJArI

## 📦 Install Dependencies
"""

!pip install -q accelerate bitsandbytes datasets huggingface_hub peft scikit-learn transformers trl

"""## 📚 Libraries"""

from collections import Counter
from datasets import load_dataset
from google.colab import userdata
from huggingface_hub import login
import numpy as np, os, random, torch
from torch.nn import CrossEntropyLoss
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    classification_report, confusion_matrix
)

from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,
    TrainingArguments, Trainer
)
from peft import LoraConfig, get_peft_model, PeftModel

"""🔕 Disable Weights & Biases"""

os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "offline"

"""## 🔐 Login to Hugging Face Hub"""

hf_token = os.environ.get('HF_Token') or userdata.get('HF_Token')

if hf_token:
    login(token=hf_token)
    print("HuggingFace login successful.")
else:
    print("HuggingFace token not found. Please set the HF_TOKEN environment variable or store it in Colab secrets.")

dataset = load_dataset("dair-ai/emotion")

emotion_map = {
    0: "sadness", 1: "joy", 2: "love",
    3: "anger", 4: "fear", 5: "surprise"
}

def convert_label(ex):
    ex["emotion"] = emotion_map[ex["label"]]
    return ex

dataset["train"] = dataset["train"].map(convert_label)
dataset["test"]  = dataset["test"].map(convert_label)

"""## 📥 Load dair-ai/emotion Dataset"""

dataset = load_dataset("dair-ai/emotion")

emotion_map = {
    0: "sadness", 1: "joy", 2: "love",
    3: "anger", 4: "fear", 5: "surprise"
}

def convert_label(ex):
    ex["emotion"] = emotion_map[ex["label"]]
    return ex

dataset["train"] = dataset["train"].map(convert_label)
dataset["test"]  = dataset["test"].map(convert_label)

"""⚖️ Inspect Dataset Balance"""

label_counts = Counter(dataset["train"]["label"])
print("\nLabel counts in train:")
print(label_counts)

"""⚖️ Class Weights"""

counts = torch.tensor([4666, 5362, 1304, 2159, 1937, 572], dtype=torch.float)
weights = 1.0 / counts
weights = weights / weights.sum()          # normalized weights

print("\nClass weights:", weights)

"""The dataset is unbalanced.  And so I add class weights (loss weights) so that more rare classes have more weight

🧠 Options & Global Constants
"""

OPTIONS = ["sadness", "joy", "love", "anger", "fear", "surprise"]
label2id = {label: i for i, label in enumerate(OPTIONS)}

"""## 🧩 Create Prompts from Tabular Data


"""

def row_to_prompt(example):
    options_text = "\n".join(f"- {opt}" for opt in OPTIONS)
    prompt = (
        "You are an expert in emotion classification.\n\n"
        f"Text:\n{example['text']}\n\n"
        f"Options:\n{options_text}\n\n"
        "Answer with exactly one option from the list."
    )
    return {
        "prompt": prompt,
        "label_id": label2id[example["emotion"]],
    }

train_ds = dataset["train"].map(row_to_prompt)
test_ds  = dataset["test"].map(row_to_prompt)

print("\nExample prompt row:")
print(train_ds[0])

"""🧪 Reproducibility"""

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

"""🧠 Shared Tokenizer"""

MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"

tok = AutoTokenizer.from_pretrained(
    MODEL_ID,
    token=hf_token,
    use_fast=True,
)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

# We'll classify by looking only at these token IDs
answer_token_ids = [
    tok(opt, add_special_tokens=False).input_ids[-1]
    for opt in OPTIONS
]
answer_token_ids_tensor = torch.tensor(answer_token_ids, dtype=torch.long)

"""🔢 Tokenize for Training"""

def tokenize_fn(batch):
    enc = tok(
        batch["prompt"],
        truncation=True,
        padding="max_length",
        max_length=512,
    )
    enc["labels"] = batch["label_id"]  # class index 0..5
    return enc

train_encoded = train_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=train_ds.column_names,
)
test_encoded = test_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=test_ds.column_names,
)

# Make datasets return torch tensors
train_encoded.set_format(type="torch")
test_encoded.set_format(type="torch")

"""🧠 Baseline Model (Unfine-tuned)"""

baseline_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    token=hf_token,
)
print("\nLoaded baseline_model (unfine-tuned).")

"""📊 Shared Evaluation Function"""

def evaluate_model(model, ds_with_prompts, name: str, n_preview: int = 500):
    """
    Evaluate a model using the same "next-token over OPTIONS" trick.
    Uses ds_with_prompts (with 'prompt' + 'label_id').
    """
    model.eval()
    N = min(n_preview, len(ds_with_prompts))

    y_true, y_pred = [], []

    for i in range(N):
        ex = ds_with_prompts[i]
        prompt = ex["prompt"]
        label_id = ex["label_id"]

        inputs = tok(prompt, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model(**inputs)
            logits_full = outputs.logits[:, -1, :]                     # [1, vocab]
            option_logits = logits_full[:, answer_token_ids_tensor]    # [1, 6]
            pred_class = option_logits.argmax(dim=-1).item()

        y_true.append(label_id)
        y_pred.append(pred_class)

    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    print(f"\n====== {name} (N={N}) ======")
    print(f"Acc={acc:.3f}  Prec={prec:.3f}  Rec={rec:.3f}  F1={f1:.3f}\n")
    print("Classification report:")
    print(classification_report(y_true, y_pred, target_names=OPTIONS, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    print("\nConfusion matrix (rows=true, cols=pred):")
    print("   " + "  ".join(OPTIONS))
    for i, row in enumerate(cm):
        print(f"{OPTIONS[i]:8s} {row}")

    return y_true, y_pred, cm

"""📊 Baseline Evaluation"""

_ = evaluate_model(baseline_model, test_ds, name="Baseline (unfine-tuned)")

"""⚙️ QLoRA Base Model (4-bit) for Training"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

sft_base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    token=hf_token,
)
print("\nLoaded sft_base_model (4-bit, QLoRA-ready).")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

sft_model = get_peft_model(sft_base_model, lora_config)
print("Wrapped sft_base_model with LoRA → sft_model.")

"""🛠️ Custom Trainer with loss_fn"""

class WeightedLossTrainer(Trainer):
    """
    Custom Trainer that:
    - Uses class-weighted CrossEntropyLoss
    - Only uses logits over the 6 emotion option tokens
    """
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")                             # [batch]
        outputs = model(**inputs)
        logits_full = outputs.logits                              # [batch, seq_len, vocab]
        last_logits = logits_full[:, -1, :]                       # [batch, vocab]
        option_logits = last_logits[:, answer_token_ids_tensor]   # [batch, 6]

        # Put weights and labels are on the same device as logits
        device = option_logits.device
        weighted_ce = CrossEntropyLoss(weight=weights.to(device))
        loss = weighted_ce(option_logits, labels.to(device))

        if return_outputs:
            return loss, outputs
        return loss

"""🎯 Training Arguments"""

training_args = TrainingArguments(
    output_dir="emotion-llama-qlora",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=1e-4,
    num_train_epochs=1,
    bf16=True,
    logging_steps=50,
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    report_to="none",   # disable wandb etc.
)

"""🚀 Train"""

trainer = WeightedLossTrainer(
    model=sft_model,
    args=training_args,
    train_dataset=train_encoded,
    eval_dataset=test_encoded,
    tokenizer=tok,
)

print("\nFinished QLoRA fine-tuning; sft_model is trained.")

"""🚀 QLoRA Fine-Tuning"""

trainer.train()

"""💾 Save LoRA"""

adapter_dir = "emotion-llama-qlora"
sft_model.save_pretrained(adapter_dir)
tok.save_pretrained(adapter_dir)
print(f"\nSaved LoRA adapter + tokenizer to: {adapter_dir}")

sft_model.push_to_hub("david125tran/emotion-llama-qlora")
tok.push_to_hub("david125tran/emotion-llama-qlora")

"""🔄 Reload Fine-Tuned Model for Evaluation"""

reload_base = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,   # use same 4-bit config
    device_map="auto",
    token=hf_token,
)

sft_model_reloaded = PeftModel.from_pretrained(
    reload_base,
    "david125tran/emotion-llama-qlora",
)
print("\nReloaded sft_model_reloaded from Hub.")

"""📊 Evaluate Fine-Tuned"""

_ = evaluate_model(sft_model_reloaded, test_ds, name="Supervised Fine-Tuning Model")