# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qE5BcG9C4BQZnNy2k6aRY3bn2OklJArI

## 📦 Install Dependencies
"""

!pip install -q accelerate bitsandbytes datasets huggingface_hub peft scikit-learn transformers trl

"""## 📚 Libraries"""

from collections import Counter
from datasets import load_dataset
from google.colab import userdata
from huggingface_hub import login

import os
import random
import numpy as np
import torch
from torch.nn import CrossEntropyLoss

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    default_data_collator,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
)

from peft import LoraConfig, get_peft_model, PeftModel

"""🔕 Disable Weights & Biases"""

os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "offline"

"""## 🔐 Login to Hugging Face Hub"""

hf_token = os.environ.get('HF_Token') or userdata.get('HF_Token')

if hf_token:
    login(token=hf_token)
    print("HuggingFace login successful.")
else:
    print("HuggingFace token not found. Please set the HF_TOKEN environment variable or store it in Colab secrets.")

"""## 📥 Load dair-ai/emotion Dataset"""

dataset = load_dataset("dair-ai/emotion")

emotion_map = {
    0: "sadness", 1: "joy", 2: "love",
    3: "anger",   4: "fear", 5: "surprise"
}

def convert_label(ex):
    ex["emotion"] = emotion_map[int(ex["label"])]
    return ex

dataset["train"] = dataset["train"].map(convert_label)
dataset["test"]  = dataset["test"].map(convert_label)

"""⚖️ Inspect Dataset Balance"""

label_counts = Counter(dataset["train"]["label"])
print("\nLabel counts in train:", label_counts)

"""⚖️ Class Weights"""

counts = torch.tensor([label_counts[i] for i in range(6)], dtype=torch.float)
weights = 1.0 / counts
# I keep mean=1 so the overall loss scale stays reasonable
weights = weights / weights.mean()

print("\nClass weights:", weights)

"""The dataset is unbalanced.  And so I add class weights (loss weights) so that more rare classes have more weight

🧠 Options & Global Constants
"""

OPTIONS = ["sadness", "joy", "love", "anger", "fear", "surprise"]
label2id = {label: i for i, label in enumerate(OPTIONS)}

"""## 🧩 Create Prompts from Tabular Data


"""

def row_to_prompt(example):
    options_text = "\n".join(f"- {opt}" for opt in OPTIONS)
    prompt = (
        "You are an expert in emotion classification.\n\n"
        f"Text:\n{example['text']}\n\n"
        f"Options:\n{options_text}\n\n"
        "Answer with exactly one option from the list."
    )
    return {
        "prompt": prompt,
        "label_id": label2id[example["emotion"]],
    }

train_ds = dataset["train"].map(row_to_prompt)
test_ds  = dataset["test"].map(row_to_prompt)

print("\nExample prompt row:\n")
print(train_ds[0]["prompt"])
print("label_id:", train_ds[0]["label_id"])

"""🧪 Reproducibility"""

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

"""Hardware Configuration"""

use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
compute_dtype = torch.bfloat16 if use_bf16 else torch.float16
print(f"\nUsing bf16? {use_bf16}  | compute_dtype={compute_dtype}")

"""🧠 Shared Tokenizer"""

MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"

tok = AutoTokenizer.from_pretrained(
    MODEL_ID,
    token=hf_token,
    use_fast=True,
)

# pad token setup (important for batching)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

# We'll classify by looking only at these token IDs
# NOTE: This is still a "last-token" trick — it's simple and fast, but not perfect.
answer_token_ids = [
    tok(opt, add_special_tokens=False).input_ids[-1]
    for opt in OPTIONS
]
answer_token_ids_tensor = torch.tensor(answer_token_ids, dtype=torch.long)

"""🔢 Tokenize for Training"""

MAX_LEN = 512

def tokenize_fn(batch):
    enc = tok(
        batch["prompt"],
        truncation=True,
        padding="max_length",   # simple + predictable
        max_length=MAX_LEN,
    )
    enc["labels"] = batch["label_id"]  # class index 0..5
    return enc

train_encoded = train_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=train_ds.column_names,
)
test_encoded = test_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=test_ds.column_names,
)

train_encoded.set_format(type="torch")
test_encoded.set_format(type="torch")

"""🧠 Baseline Model (Unfine-tuned)"""

baseline_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map="auto",
    torch_dtype=compute_dtype,
    token=hf_token,
)
print("\nLoaded baseline_model (unfine-tuned).")

"""📊 Shared Evaluation Function"""

def evaluate_model(model, ds_with_prompts, name: str, n_preview: int = 500):
    """
    Evaluate using the same "next-token over options" trick:
      - Run model on prompt
      - Grab logits at the final position
      - Compare logits for the 6 option tokens
    """
    model.eval()
    N = min(n_preview, len(ds_with_prompts))

    y_true, y_pred = [], []

    for i in range(N):
        ex = ds_with_prompts[i]
        prompt = ex["prompt"]
        label_id = ex["label_id"]

        inputs = tok(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=MAX_LEN,
        ).to(model.device)

        with torch.no_grad():
            outputs = model(**inputs)

            # last non-pad token index (safe even if we pad later)
            attn = inputs["attention_mask"]  # [1, T]
            last_idx = int(attn.sum(dim=1).item() - 1)

            logits_full = outputs.logits[:, last_idx, :]                  # [1, vocab]
            option_logits = logits_full[:, answer_token_ids_tensor.to(model.device)]  # [1, 6]
            pred_class = option_logits.argmax(dim=-1).item()

        y_true.append(label_id)
        y_pred.append(pred_class)

    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    print(f"\n====== {name} (N={N}) ======")
    print(f"Acc={acc:.3f}  Prec={prec:.3f}  Rec={rec:.3f}  F1={f1:.3f}\n")
    print("Classification report:")
    print(classification_report(y_true, y_pred, target_names=OPTIONS, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    print("\nConfusion matrix (rows=true, cols=pred):")
    print("   " + "  ".join(OPTIONS))
    for r, row in enumerate(cm):
        print(f"{OPTIONS[r]:8s} {row}")

    return y_true, y_pred, cm

"""📊 Baseline Evaluation"""

baseline_evaluation = evaluate_model(baseline_model, test_ds, name="Baseline (unfine-tuned)")

"""⚙️ QLoRA Base Model (4-bit) for Training"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
)

sft_base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    token=hf_token,
)
print("\nLoaded sft_base_model (4-bit, QLoRA-ready).")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

sft_model = get_peft_model(sft_base_model, lora_config)
print("Wrapped sft_base_model with LoRA → sft_model.")

"""🛠️ Custom Trainer with loss_fn"""

class WeightedLossTrainer(Trainer):
    """
    Trainer that:
    - Uses class-weighted CrossEntropyLoss
    - Scores only logits over the 6 emotion option tokens
    - Uses attention_mask to find the real last token (with max_length padding)
    """
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs["labels"]  # [B]
        outputs = model(**{k: v for k, v in inputs.items() if k != "labels"})

        logits_full = outputs.logits  # [B, T, vocab]

        # Find last non-padding token per row
        attn = inputs["attention_mask"]  # [B, T]
        last_idx = attn.sum(dim=1) - 1   # [B]
        batch_idx = torch.arange(attn.size(0), device=attn.device)

        last_logits = logits_full[batch_idx, last_idx, :]  # [B, vocab]
        option_logits = last_logits[:, answer_token_ids_tensor.to(last_logits.device)]  # [B, 6]

        weighted_ce = CrossEntropyLoss(weight=weights.to(option_logits.device))
        loss = weighted_ce(option_logits, labels.to(option_logits.device))

        if return_outputs:
            return loss, outputs
        return loss

"""🎯 Training Arguments"""

training_args = TrainingArguments(
    output_dir="emotion-llama-qlora",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=1e-4,
    num_train_epochs=1,
    bf16=True,
    logging_steps=50,
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    report_to="none",   # disable wandb etc.
)

"""🚀 Train"""

trainer = WeightedLossTrainer(
    model=sft_model,
    args=training_args,
    train_dataset=train_encoded,
    eval_dataset=test_encoded,
    data_collator=default_data_collator,
)

"""🚀 QLoRA Fine-Tuning"""

trainer.train()

"""💾 Save LoRA"""

adapter_dir = "emotion-llama-qlora"
sft_model.save_pretrained(adapter_dir)
tok.save_pretrained(adapter_dir)
print(f"\nSaved LoRA adapter + tokenizer to: {adapter_dir}")

sft_model.push_to_hub("david125tran/emotion-llama-qlora")
tok.push_to_hub("david125tran/emotion-llama-qlora")

"""🔄 Reload Fine-Tuned Model for Evaluation"""

reload_base = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,   # use same 4-bit config
    device_map="auto",
    token=hf_token,
)

sft_model_reloaded = PeftModel.from_pretrained(
    reload_base,
    "david125tran/emotion-llama-qlora",
)
print("\nReloaded sft_model_reloaded from Hub.")

"""📊 Evaluate Fine-Tuned"""

ft_evaulated = evaluate_model(sft_model_reloaded, test_ds, name="Supervised Fine-Tuning Model")